# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e769391e479084716320919d4d756cbdc12a5e45b9de537f63c8bc77a20c0e4460c46b4c1b0e68c97c233a56dc36f4834975b99a0df32b50b047602bcb3579db

test:
  secret_key_base: 53e3beeca217aa54733a78e56ca0564c6eacf7d3d287f4f03237fe3e68e087be79224f9e25e09257fb5ec4579094674c9226da1ce70fe9c7b6bbe1c0dee26b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
